#!/usr/bin/env python3
"""
Write STAT AxisValueArray, fvar named instances, and related name table entries.
"""

from __future__ import annotations

import itertools
from io import StringIO
from typing import List, Set

from fontTools.ttLib import TTFont
from fontTools.ttLib.tables._f_v_a_r import NamedInstance
from fontTools.ttLib.tables.otTables import AxisValue, AxisValueArray

from vfcommit_lib.logging_config import get_logger
from vfcommit_lib.nameid_allocator import (
    AxisDef,
    CompoundStatValueDef,
    NameIDPlan,
    compose_instance_name,
    compose_name_from_order,
)

logger = get_logger(__name__)

STAT_VERSION_12 = 0x00010002
OLDER_SIBLING_FLAG = 0x0001
ELIDABLE_FLAG = 0x0002


def _stat_flags(elidable: bool, older_sibling: bool = False) -> int:
    flags = 0
    if older_sibling:
        flags |= OLDER_SIBLING_FLAG
    if elidable:
        flags |= ELIDABLE_FLAG
    return flags


def build_protected_name_ids(font: TTFont, ot_label_ids: Set[int]) -> Set[int]:
    """NameIDs that must survive wipe (OT labels, fvar/STAT axis names)."""
    protected = set(ot_label_ids)
    if "fvar" in font:
        for axis in font["fvar"].axes:
            if axis.axisNameID >= 256:
                protected.add(axis.axisNameID)
    if "STAT" in font:
        stat = font["STAT"].table
        design = getattr(stat, "DesignAxisRecord", None)
        if design and design.Axis:
            for axis in design.Axis:
                if axis.AxisNameID >= 256:
                    protected.add(axis.AxisNameID)
    return protected


def count_existing_stat_axis_values(font: TTFont) -> int:
    if "STAT" not in font:
        return 0
    stat = font["STAT"].table
    array = getattr(stat, "AxisValueArray", None)
    if not array or not array.AxisValue:
        return 0
    return len(array.AxisValue)


def _wipe_existing_table_data(font: TTFont, protected_ids: Set[int]) -> None:
    """Clear fvar instances, STAT axis values, and non-protected name IDs ≥ 256."""
    if "fvar" in font:
        font["fvar"].instances = []

    if "STAT" in font:
        stat = font["STAT"].table
        avarray = AxisValueArray()
        avarray.AxisValue = []
        stat.AxisValueArray = avarray

    name_table = font["name"]
    name_table.names = [
        rec
        for rec in name_table.names
        if rec.nameID < 256 or rec.nameID in protected_ids
    ]


def apply_table_edits(
    font: TTFont,
    axis_defs: List[AxisDef],
    plan: NameIDPlan,
    elided_fallback_name: str = "Regular",
    protected_ids: Set[int] | None = None,
    confirm_wipe: bool = False,
    ot_label_count: int = 0,
    instance_axis_defs: List[AxisDef] | None = None,
    pinned_coords: dict[str, float] | None = None,
    compound_defs: List[CompoundStatValueDef] | None = None,
    included_instance_keys: List[str] | None = None,
) -> None:
    """
    Write all changes to the font in memory. Does not save.

    Order: optional wipe confirmation → wipe → name records
    → fvar instances → STAT. DesignAxisRecord is preserved (not wiped).
    fvar axis min/default/max are never rewritten.
    """
    if protected_ids is None:
        protected_ids = set()

    if confirm_wipe:
        confirm_wipe_and_rebuild(
            font,
            protected_ids,
            ot_label_count=ot_label_count,
        )

    _wipe_existing_table_data(font, protected_ids)

    _write_name_records(font, axis_defs, plan)
    _repoint_fvar_axis_names(font, plan.axis_name_ids)
    # fvar axis min/default/max are design-space metadata — never rewrite on save.
    grid_axes = instance_axis_defs if instance_axis_defs is not None else axis_defs
    _write_fvar_instances(
        font,
        grid_axes,
        plan,
        elided_fallback_name,
        pinned_coords=pinned_coords,
        included_instance_keys=included_instance_keys,
    )
    _write_stat(
        font,
        axis_defs,
        plan,
        elided_fallback_name,
        compound_defs=compound_defs or [],
    )


def generate_ttx_additions(
    font: TTFont,
    axis_defs: List[AxisDef],
    plan: NameIDPlan,
    elided_fallback_name: str = "Regular",
) -> str:
    """
    Return TTX XML for updated name, fvar, and STAT tables.

    Note: emits full post-edit table XML (not a minimal diff fragment). Suitable
    for inspection or merge-by-hand; a true additions-only export is future work.
    """
    instance_count = count_instances(axis_defs)
    parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- Generated by VariableFont_TableEditor -->",
        f"<!-- instances={instance_count} elided_fallback={elided_fallback_name!r} "
        f"nameIDs={plan.free_start}-{plan.free_end} -->",
        "<ttFont>",
    ]
    for tag in ("name", "fvar", "STAT"):
        if tag not in font:
            continue
        writer = StringIO()
        font[tag].toXML(writer, font)
        parts.append(writer.getvalue().rstrip())
    parts.append("</ttFont>")
    return "\n".join(parts) + "\n"


def _repoint_fvar_axis_names(font: TTFont, axis_name_ids: dict[str, int]) -> None:
    if "fvar" not in font:
        return
    for axis in font["fvar"].axes:
        new_id = axis_name_ids.get(axis.axisTag)
        if new_id is not None:
            axis.axisNameID = new_id


def _write_name_records(font: TTFont, axis_defs: List[AxisDef], plan: NameIDPlan) -> None:
    name_table = font["name"]

    prefix = (plan.family_ps_prefix or "").strip()
    if prefix:
        name_table.setName(prefix, 25, 3, 1, 0x0409)

    # Order matches allocation: DesignAxis → AxisValues → compounds → EFB → fvar (+ PS).
    for tag, nid in plan.axis_name_ids.items():
        name_table.setName(plan.axis_names.get(tag, tag), nid, 3, 1, 0x0409)

    for axis_def in axis_defs:
        for av_def in axis_def.values:
            key = (axis_def.tag, av_def.value)
            nid = plan.axis_value_ids[key]
            label = plan.stat_value_labels.get(key, av_def.name)
            name_table.setName(label, nid, 3, 1, 0x0409)

    for compound_id, nid in plan.compound_value_ids.items():
        label = plan.compound_value_names.get(compound_id, compound_id)
        name_table.setName(label, nid, 3, 1, 0x0409)

    if plan.elided_fallback_id:
        name_table.setName(
            plan.elided_fallback_name, plan.elided_fallback_id, 3, 1, 0x0409
        )

    for composed_name, nid in plan.instance_ids.items():
        name_table.setName(composed_name, nid, 3, 1, 0x0409)

    for composed_name, ps_nid in plan.instance_postscript_ids.items():
        ps_name = plan.instance_postscript_names.get(composed_name)
        if ps_name:
            name_table.setName(ps_name, ps_nid, 3, 1, 0x0409)


def _write_fvar_instances(
    font: TTFont,
    axis_defs: List[AxisDef],
    plan: NameIDPlan,
    elided_fallback_name: str = "Regular",
    *,
    pinned_coords: dict[str, float] | None = None,
    included_instance_keys: List[str] | None = None,
) -> None:
    from vfcommit_lib.request_bridge import instance_key

    fvar = font["fvar"]
    fvar.instances = []

    value_lists = [ad.values for ad in axis_defs]
    tag_list = [ad.tag for ad in axis_defs]
    allowed = set(included_instance_keys) if included_instance_keys else None
    pinned = pinned_coords or {}

    for combo in itertools.product(*value_lists):
        coords = {tag: float(av.value) for tag, av in zip(tag_list, combo)}
        if pinned_coords:
            coords.update(pinned_coords)
        if allowed is not None:
            merged = dict(coords)
            for tag, value in pinned.items():
                merged.setdefault(tag, float(value))
            if instance_key(merged) not in allowed:
                continue
        composed = compose_instance_name(
            combo,
            elided_fallback_name,
            naming_order=plan.naming_order,
            clarifiers=plan.clarifiers,
            axis_tags=tag_list,
            axes_json=plan.axes_json,
            file_stat_registration=plan.file_stat_registration,
        )

        inst = NamedInstance()
        inst.coordinates = coords
        inst.subfamilyNameID = plan.instance_ids[composed]
        ps_nid = plan.instance_postscript_ids.get(composed)
        inst.postscriptNameID = ps_nid if ps_nid is not None else 0xFFFF
        fvar.instances.append(inst)


def _write_stat(
    font: TTFont,
    axis_defs: List[AxisDef],
    plan: NameIDPlan,
    elided_fallback_name: str,
    compound_defs: List[CompoundStatValueDef] | None = None,
) -> None:
    if "STAT" not in font:
        raise ValueError("Font has no STAT table")

    stat_table = font["STAT"].table
    if stat_table.Version < STAT_VERSION_12:
        stat_table.Version = STAT_VERSION_12

    # Repoint DesignAxisRecord axis names to the freshly allocated 256+ IDs
    design = getattr(stat_table, "DesignAxisRecord", None)
    if design and design.Axis:
        for ax in design.Axis:
            new_nid = plan.axis_name_ids.get(ax.AxisTag)
            if new_nid is not None:
                ax.AxisNameID = new_nid

    axis_values: List[AxisValue] = []

    for axis_def in axis_defs:
        for av_def in axis_def.values:
            av = AxisValue()
            av.Format = av_def.stat_format
            av.AxisIndex = _axis_index(stat_table, axis_def.tag)
            av.Flags = _stat_flags(av_def.elidable, av_def.older_sibling)
            av.ValueNameID = plan.axis_value_ids[(axis_def.tag, av_def.value)]

            if av_def.stat_format == 1:
                av.Value = float(av_def.value)
            elif av_def.stat_format == 2:
                if av_def.range_min is None or av_def.range_max is None:
                    raise ValueError(
                        f"Format 2 axis value {axis_def.tag}={av_def.value} "
                        "requires range_min and range_max"
                    )
                av.RangeMinValue = float(av_def.range_min)
                av.NominalValue = float(av_def.value)
                av.RangeMaxValue = float(av_def.range_max)
            elif av_def.stat_format == 3:
                av.Value = float(av_def.value)
                if av_def.linked_value is None:
                    raise ValueError(
                        f"Format 3 axis value {axis_def.tag}={av_def.value} "
                        "requires linked_value"
                    )
                av.LinkedValue = float(av_def.linked_value)
            else:
                raise ValueError(f"Unsupported STAT AxisValue format {av_def.stat_format}")

            axis_values.append(av)

    for compound in compound_defs or []:
        av = AxisValue()
        av.Format = 4
        av.AxisCount = len(compound.axis_indices)
        av.AxisIndex = list(compound.axis_indices)
        av.Flags = _stat_flags(compound.elidable, compound.older_sibling)
        av.ValueNameID = plan.compound_value_ids[compound.id]
        av.AxisValue = [float(value) for value in compound.axis_values]
        axis_values.append(av)

    avarray = AxisValueArray()
    avarray.AxisValue = axis_values
    stat_table.AxisValueArray = avarray

    # Always a freshly allocated 256+ ID (never reuse ID 2 or an instance nameID)
    efb_nid = plan.elided_fallback_id
    if not efb_nid:
        raise ValueError("No elided fallback nameID allocated in plan")
    stat_table.ElidedFallbackNameID = efb_nid


def _axis_index(stat_table, axis_tag: str) -> int:
    if not hasattr(stat_table, "DesignAxisRecord") or not stat_table.DesignAxisRecord:
        raise ValueError("STAT has no DesignAxisRecord")
    for i, ax in enumerate(stat_table.DesignAxisRecord.Axis):
        if ax.AxisTag == axis_tag:
            return i
    raise ValueError(f"Axis tag '{axis_tag}' not found in STAT DesignAxisRecord")


def count_instances(axis_defs: List[AxisDef]) -> int:
    """Total fvar instance count from axis value cartesian product."""
    if not axis_defs:
        return 0
    n = 1
    for ad in axis_defs:
        n *= len(ad.values)
    return n


def confirm_wipe_and_rebuild(
    font: TTFont,
    protected_ids: Set[int],
    *,
    ot_label_count: int = 0,
) -> None:
    """Interactive wipe prompt is not available in vfcommit; use dry-run or confirm_wipe=False."""
    raise NotImplementedError(
        "confirm_wipe_and_rebuild is not supported in vfcommit; "
        "use dry_run preview or apply_table_edits(..., confirm_wipe=False)"
    )


__all__ = [
    "apply_table_edits",
    "build_protected_name_ids",
    "confirm_wipe_and_rebuild",
    "count_existing_stat_axis_values",
    "generate_ttx_additions",
    "count_instances",
]
